from autogen_agentchat.teams import DiGraphBuilder, GraphFlow
import asyncio
import os
from dotenv import load_dotenv

from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.conditions import TextMentionTermination
from autogen_agentchat.messages import TextMessage

from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import ModelInfo

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
MODEL_NAME = os.getenv("GEMINI_MODEL")


# ============================================================
# MODEL CLIENT
# ============================================================
model_client = OpenAIChatCompletionClient(
    model=MODEL_NAME,
    api_key=GOOGLE_API_KEY,
    api_type="google",
    temperature=0.2,
    parallel_tool_calls=False,   # IMPORTANT FOR GEMINI
    model_info=ModelInfo(
        vision=True,
        function_calling=True,
        json_output=False,
        structured_output=False,
        family="unknown"
    )
)

writer = AssistantAgent(
    name = "writer",
    description = "A writer agent that generates a story based on a user's prompt.",
    model_client=model_client,
    system_message="You are a writer. Write a story based on the user's prompt. Keep it concise and engaging."
)

reviewer = AssistantAgent(
    name = "reviewer",
    description = "A reviewer agent that reviews the story generated by the writer and provides feedback.",
    model_client=model_client,
    system_message="You are a reviewer. Please provide feedback on the text generated by the writer."
)

builder = DiGraphBuilder()
builder.add_node(writer).add_node(reviewer)
builder.add_edge(writer, reviewer)
graph = builder.build()

team = GraphFlow([writer, reviewer], graph)
stream = team.run_stream(task = "write a good poem about India")

async def main():
    async for event in stream:
        print(f"Event: {event}")
        
if __name__ == "__main__":
    asyncio.run(main())







