import re
from autogen_agentchat.teams import DiGraphBuilder, GraphFlow
import asyncio
import os
from dotenv import load_dotenv
from autogen_agentchat.ui import Console

from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.conditions import TextMentionTermination
from autogen_agentchat.messages import TextMessage

from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import ModelInfo

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
MODEL_NAME = os.getenv("GEMINI_MODEL")


# ============================================================
# MODEL CLIENT
# ============================================================
model_client = OpenAIChatCompletionClient(
    model=MODEL_NAME,
    api_key=GOOGLE_API_KEY,
    api_type="google",
    temperature=0.2,
    parallel_tool_calls=False,   # IMPORTANT FOR GEMINI
    model_info=ModelInfo(
        vision=True,
        function_calling=True,
        json_output=False,
        structured_output=False,
        family="unknown"
    )
)

writer = AssistantAgent(
    name = "writer",
    description = "A writer agent that generates a story based on a user's prompt.",
    model_client=model_client,
    system_message="You are a writer. Write a story based on climate change. Max 100 words only"

)

editor1 = AssistantAgent(
    name = "editor1",
    description = "An editor agent that reviews the story generated by the writer and provides feedback.",
    model_client=model_client,
    system_message = " Edit the paragraph for Grammar"
)

editor2 = AssistantAgent(
    name = "editor2",   
    description = "An editor agent that reviews the story generated by the writer and provides feedback.",
    model_client=model_client,  
    system_message = " Edit the paragraph for Style. Tell the changes in point structure"
)

reviewer = AssistantAgent(
    name = "reviewer",
    description = "A reviewer agent that reviews the story generated by the writer and provides feedback.",
    model_client=model_client,
    system_message="Consolidate the Grammar and edits into a final version"
)

builder = DiGraphBuilder()
builder.add_node(writer).add_node(editor1).add_node(editor2).add_node(reviewer)
#Fan out from writer to editor
builder.add_edge(writer, editor1)
builder.add_edge(writer, editor2)
#fan out from editors to reviewer
builder.add_edge(editor1, reviewer)
builder.add_edge(editor2, reviewer)

graph = builder.build()
print(graph)

flow = GraphFlow(participants = builder.get_participants(), graph = graph)

async def main():
    await  Console(flow.run_stream(task = "write a good story about climate change"))

if __name__ == "__main__":
    asyncio.run(main())